import java.util.HashMap;
import java.util.Map;

public class TwitterTimezones {
	public static Map<String,String> countryCodes=new HashMap<String,String>();
	public static Map<String,String> countries=new HashMap<String,String>();
	static{
		countryCodes.put("Monterrey","MX");
		countryCodes.put("Eastern Time (US & Canada)","US");
		countryCodes.put("Paris","FR");
		countryCodes.put("Atlantic Time (Canada)","CA");
		countryCodes.put("Seoul","KR");
		countryCodes.put("Cape Verde Is.","MR");
		countryCodes.put("Perth","AU");
		countryCodes.put("Kuala Lumpur","MY");
		countryCodes.put("Indiana (East)","US");
		countryCodes.put("Santiago","CL");
		countryCodes.put("Chennai","IN");
		countryCodes.put("Azores","PT");
		countryCodes.put("Abu Dhabi","AE");
		countryCodes.put("Mountain Time (US & Canada)","US");
		countryCodes.put("Skopje","MK");
		countryCodes.put("Ekaterinburg","RU");
		countryCodes.put("Brussels","BE");
		countryCodes.put("Kamchatka","RU");
		countryCodes.put("Marshall Is.","MH");
		countryCodes.put("Solomon Is.","SB");
		countryCodes.put("Dublin","IE");
		countryCodes.put("Alaska","US");
		countryCodes.put("Rome","IT");
		countryCodes.put("Sri Jayawardenepura","LK");
		countryCodes.put("Taipei","TW");
		countryCodes.put("Greenland","GL");
		countryCodes.put("Samoa","WS");
		countryCodes.put("Casablanca","MA");
		countryCodes.put("Brisbane","AU");
		countryCodes.put("Cairo","EG");
		countryCodes.put("Osaka","JP");
		countryCodes.put("London","GB");
		countryCodes.put("Vilnius","LT");
		countryCodes.put("Vladivostok","RU");
		countryCodes.put("Caracas","VE");
		countryCodes.put("Harare","ZW");
		countryCodes.put("Guadalajara","MX");
		countryCodes.put("Pacific Time (US & Canada)","US");
		countryCodes.put("Midway Island","WS");
		countryCodes.put("Sydney","AU");
		countryCodes.put("Kolkata","IN");
		countryCodes.put("Vienna","AT");
		countryCodes.put("Edinburgh","GB");
		countryCodes.put("Arizona","US");
		countryCodes.put("Quito","EC");
		countryCodes.put("Singapore","SG");
		countryCodes.put("Saskatchewan","CA");
		countryCodes.put("Moscow","RU");
		countryCodes.put("Mid-Atlantic","CA");
		countryCodes.put("Bratislava","SK");
		countryCodes.put("Berlin","DE");
		countryCodes.put("Tehran","IR");
		countryCodes.put("Bern","CH");
		countryCodes.put("Astana","KZ");
		countryCodes.put("Karachi","PK");
		countryCodes.put("Brasilia","BR");
		countryCodes.put("Nuku'alofa","TO");
		countryCodes.put("New Caledonia","NC");
		countryCodes.put("Monrovia","LR");
		countryCodes.put("Kathmandu","NP");
		countryCodes.put("Central Time (US & Canada)","US");
		countryCodes.put("Pretoria","ZA");
		countryCodes.put("Newfoundland","CA");
		countryCodes.put("New Delhi","IN");
		countryCodes.put("Madrid","ES");
		countryCodes.put("Baku","AZ");
		countryCodes.put("Novosibirsk","RU");
		countryCodes.put("Adelaide","AU");
		countryCodes.put("Mexico City","MX");
		countryCodes.put("Chihuahua","MX");
		countryCodes.put("Istanbul","TR");
		countryCodes.put("Kuwait","KW");
		countryCodes.put("Hanoi","VN");
		countryCodes.put("St. Petersburg","RU");
		countryCodes.put("Mazatlan","MX");
		countryCodes.put("Kyiv","UA");
		countryCodes.put("Krasnoyarsk","RU");
		countryCodes.put("Ljubljana","SI");
		countryCodes.put("Muscat","OM");
		countryCodes.put("Auckland","NZ");
		countryCodes.put("Baghdad","IQ");
		countryCodes.put("Hobart","AU");
		countryCodes.put("Ulaan Bataar","MN");
		countryCodes.put("Hong Kong","HK");
		countryCodes.put("Rangoon","MM");
		countryCodes.put("Helsinki","FI");
		countryCodes.put("Islamabad","PK");
		countryCodes.put("Yakutsk","RU");
		countryCodes.put("Wellington","NZ");
		countryCodes.put("Stockholm","SE");
		countryCodes.put("Guam","AU");
		countryCodes.put("Nairobi","KE");
		countryCodes.put("Yerevan","AM");
		countryCodes.put("Bucharest","RO");
		countryCodes.put("Beijing","CN");
		countryCodes.put("Canberra","AU");
		countryCodes.put("Central America","MX");
		countryCodes.put("Volgograd","RU");
		countryCodes.put("Lima","PE");
		countryCodes.put("Fiji","FJ");
		countryCodes.put("Mumbai","IN");
		countryCodes.put("Riga","LV");
		countryCodes.put("Athens","GR");
		countryCodes.put("Kabul","AF");
		countryCodes.put("Port Moresby","PG");
		countryCodes.put("Tallinn","EE");
		countryCodes.put("Darwin","AU");
		countryCodes.put("Georgetown","MY");
		countryCodes.put("Tashkent","UZ");
		countryCodes.put("Zagreb","HR");
		countryCodes.put("Tokyo","JP");
		countryCodes.put("Buenos Aires","AR");
		countryCodes.put("Bangkok","TH");
		countryCodes.put("West Central Africa","ZA");
		countryCodes.put("Chongqing","CN");
		countryCodes.put("Dhaka","BD");
		countryCodes.put("Budapest","HU");
		countryCodes.put("Jakarta","ID");
		countryCodes.put("Hawaii","US");
		countryCodes.put("Urumqi","CN");
		countryCodes.put("Melbourne","AU");
		countryCodes.put("Minsk","BY");
		countryCodes.put("Sarajevo","BA");
		countryCodes.put("Magadan","RU");
		countryCodes.put("Almaty","KZ");
		countryCodes.put("Tbilisi","GE");
		countryCodes.put("La Paz","MX");
		countryCodes.put("Tijuana","MX");
		countryCodes.put("Belgrade","BE");
		countryCodes.put("Riyadh","SA");
		countryCodes.put("Bogota","CO");
		countryCodes.put("Prague","CZ");
		countryCodes.put("Sofia","BG");
		countryCodes.put("Sapporo","JP");
		countryCodes.put("International Date Line West","US");
		countryCodes.put("Lisbon","PT");
		countryCodes.put("Amsterdam","NL");
		countryCodes.put("Copenhagen","DK");
		countryCodes.put("Jerusalem","IL");
		countryCodes.put("Irkutsk","RU");
		countryCodes.put("Warsaw","PL");



		countries.put("Monterrey","Mexico");
		countries.put("Eastern Time (US & Canada)","United States");
		countries.put("Paris","France");
		countries.put("Atlantic Time (Canada)","Canada");
		countries.put("Seoul","South Korea");
		countries.put("Cape Verde Is.","Mauritania");
		countries.put("Perth","Australia");
		countries.put("Kuala Lumpur","Malaysia");
		countries.put("Indiana (East)","United States");
		countries.put("Santiago","Chile");
		countries.put("Chennai","India");
		countries.put("Azores","Portugal");
		countries.put("Abu Dhabi","United Arab Emirates");
		countries.put("Mountain Time (US & Canada)","United States");
		countries.put("Skopje","Macedonia");
		countries.put("Ekaterinburg","Russia");
		countries.put("Brussels","Belgium");
		countries.put("Kamchatka","Russia");
		countries.put("Marshall Is.","Marshall Islands");
		countries.put("Solomon Is.","Solomon Islands");
		countries.put("Dublin","Ireland");
		countries.put("Alaska","United States");
		countries.put("Rome","Italy");
		countries.put("Sri Jayawardenepura","Sri Lanka");
		countries.put("Taipei","Taiwan");
		countries.put("Greenland","Greenland");
		countries.put("Samoa","Samoa");
		countries.put("Casablanca","Morocco");
		countries.put("Brisbane","Australia");
		countries.put("Cairo","Egypt");
		countries.put("Osaka","Japan");
		countries.put("London","United Kingdom");
		countries.put("Vilnius","Lithuania");
		countries.put("Vladivostok","Russia");
		countries.put("Caracas","Venezuela");
		countries.put("Harare","Zimbabwe");
		countries.put("Guadalajara","Mexico");
		countries.put("Pacific Time (US & Canada)","United States");
		countries.put("Midway Island","Samoa");
		countries.put("Sydney","Australia");
		countries.put("Kolkata","India");
		countries.put("Vienna","Austria");
		countries.put("Edinburgh","United Kingdom ");
		countries.put("Arizona","United States");
		countries.put("Quito","Ecuador");
		countries.put("Singapore","Singapore");
		countries.put("Saskatchewan","Canada");
		countries.put("Moscow","Russia");
		countries.put("Mid-Atlantic","Canada");
		countries.put("Bratislava","Slovakia");
		countries.put("Berlin","Germany");
		countries.put("Tehran","Iran");
		countries.put("Bern","Switzerland");
		countries.put("Astana","Kazakhstan");
		countries.put("Karachi","Pakistan");
		countries.put("Brasilia","Brazil");
		countries.put("Nuku'alofa","Tonga");
		countries.put("New Caledonia","New Caledonia");
		countries.put("Monrovia","Liberia");
		countries.put("Kathmandu","Nepal");
		countries.put("Central Time (US & Canada)","United States");
		countries.put("Pretoria","South Africa");
		countries.put("Newfoundland","Canada");
		countries.put("New Delhi","India");
		countries.put("Madrid","Spain");
		countries.put("Baku","Azerbaijan");
		countries.put("Novosibirsk","Russia");
		countries.put("Adelaide","Australia");
		countries.put("Mexico City","Mexico");
		countries.put("Chihuahua","Mexico");
		countries.put("Istanbul","Turkey");
		countries.put("Kuwait","Kuwait");
		countries.put("Hanoi","Vietnam");
		countries.put("St. Petersburg","Russia");
		countries.put("Mazatlan","Mexico");
		countries.put("Kyiv","Ukraine");
		countries.put("Krasnoyarsk","Russia");
		countries.put("Ljubljana","Slovenia");
		countries.put("Muscat","Oman");
		countries.put("Auckland","New Zealand");
		countries.put("Baghdad","Iraq");
		countries.put("Hobart","Australia");
		countries.put("Ulaan Bataar","Mongolia");
		countries.put("Hong Kong","Hong Kong");
		countries.put("Rangoon","Myanmar");
		countries.put("Helsinki","Finland");
		countries.put("Islamabad","Pakistan");
		countries.put("Yakutsk","Russia");
		countries.put("Wellington","New Zealand");
		countries.put("Stockholm","Sweden");
		countries.put("Guam","Australia");
		countries.put("Nairobi","Kenya");
		countries.put("Yerevan","Armenia");
		countries.put("Bucharest","Romania");
		countries.put("Beijing","China");
		countries.put("Canberra","Australia");
		countries.put("Central America","Mexico");
		countries.put("Volgograd","Russia");
		countries.put("Lima","Peru");
		countries.put("Fiji","Fiji");
		countries.put("Mumbai","India");
		countries.put("Riga","Latvia");
		countries.put("Athens","Greece");
		countries.put("Kabul","Afghanistan");
		countries.put("Port Moresby","Papua New Guinea");
		countries.put("Tallinn","Estonia");
		countries.put("Darwin","Australia");
		countries.put("Georgetown","Malaysia");
		countries.put("Tashkent","Uzbekistan");
		countries.put("Zagreb","Croatia");
		countries.put("Tokyo","Japan");
		countries.put("Buenos Aires","Argentina");
		countries.put("Bangkok","Thailand");
		countries.put("West Central Africa","South Africa");
		countries.put("Chongqing","China");
		countries.put("Dhaka","Bangladesh");
		countries.put("Budapest","Hungary");
		countries.put("Jakarta","Indonesia");
		countries.put("Hawaii","United States");
		countries.put("Urumqi","China");
		countries.put("Melbourne","Australia");
		countries.put("Minsk","Belarus");
		countries.put("Sarajevo","Bosnia and Herzegovina");
		countries.put("Magadan","Russia");
		countries.put("Almaty","Kazakhstan");
		countries.put("Tbilisi","Georgia");
		countries.put("La Paz","Mexico");
		countries.put("Tijuana","Mexico");
		countries.put("Belgrade","Belgium");
		countries.put("Riyadh","Saudi Arabia");
		countries.put("Bogota","Colombia");
		countries.put("Prague","Czech Republic");
		countries.put("Sofia","Bulgaria");
		countries.put("Sapporo","Japan");
		countries.put("International Date Line West","United States");
		countries.put("Lisbon","Portugal");
		countries.put("Amsterdam","Netherlands");
		countries.put("Copenhagen","Denmark");
		countries.put("Jerusalem","Israel");
		countries.put("Irkutsk","Russia");
		countries.put("Warsaw","Poland");
	}
}
